import { z } from 'zod';
import { createMcpHandler, withMcpAuth } from 'mcp-handler';
import { AuthInfo } from '@modelcontextprotocol/sdk/server/auth/types.js';
import jwt from 'jsonwebtoken';

const JWT_SECRET = process.env.JWT_SECRET!;

// MCP handler with image generation tool
const handler = createMcpHandler(
  (server) => {
    server.tool(
      'generate_image',
      'Generate an image based on a text prompt',
      {
        prompt: z.string().describe('The text prompt describing the image to generate'),
        size: z.enum(['256x256', '512x512', '1024x1024']).optional().default('1024x1024').describe('The size of the generated image'),
        style: z.enum(['natural', 'vivid']).optional().default('natural').describe('The style of the generated image'),
      },
      async ({ prompt, size, style }, extra) => {
        // TODO: Replace with actual image generation API
        const imageUrl = `https://placeholder.com/image?prompt=${encodeURIComponent(prompt)}&size=${size}`;

        const userEmail = extra.authInfo?.extra?.email || 'unknown';

        return {
          content: [
            {
              type: 'text',
              text: `Image generated successfully!\nURL: ${imageUrl}\nPrompt: ${prompt}\nSize: ${size}\nStyle: ${style}\nGenerated by: ${userEmail}`,
            },
          ],
        };
      },
    );
  },
  {},
  { basePath: '/api' },
);

// Token verification function
const verifyToken = async (
  req: Request,
  bearerToken?: string,
): Promise<AuthInfo | undefined> => {
  if (!bearerToken) return undefined;

  try {
    const decoded = jwt.verify(bearerToken, JWT_SECRET) as {
      sub: string;
      email: string;
      type: string;
    };

    if (decoded.type !== 'access') return undefined;

    return {
      token: bearerToken,
      scopes: ['generate:image'],
      clientId: decoded.sub,
      extra: {
        email: decoded.email,
      },
    };
  } catch {
    return undefined;
  }
};

// Wrap handler with OAuth authentication
const authHandler = withMcpAuth(handler, verifyToken, {
  required: true,
  requiredScopes: ['generate:image'],
  resourceMetadataPath: '/.well-known/oauth-protected-resource',
});

export { authHandler as GET, authHandler as POST, authHandler as DELETE };
