/**
 * POST /mcp
 * MCP protocol endpoint with authentication
 */

import type { VercelRequest, VercelResponse } from '@vercel/node';
import { verifyAccessToken } from '../src/auth/jwt';
import { generateImage, imageGenToolDefinition } from '../src/mcp/tools/imageGen';

// MCP Protocol types
interface JsonRpcRequest {
  jsonrpc: '2.0';
  id: string | number;
  method: string;
  params?: Record<string, unknown>;
}

interface JsonRpcResponse {
  jsonrpc: '2.0';
  id: string | number;
  result?: unknown;
  error?: {
    code: number;
    message: string;
    data?: unknown;
  };
}

export default async function handler(req: VercelRequest, res: VercelResponse) {
  // Set CORS headers
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');

  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  // Verify authentication
  const authHeader = req.headers.authorization;
  if (!authHeader || !authHeader.startsWith('Bearer ')) {
    return res.status(401).json({
      jsonrpc: '2.0',
      error: {
        code: -32001,
        message: 'Authentication required',
      },
    });
  }

  const token = authHeader.substring(7);
  let userEmail: string;

  try {
    const payload = verifyAccessToken(token);
    userEmail = payload.email;
  } catch (err) {
    return res.status(401).json({
      jsonrpc: '2.0',
      error: {
        code: -32001,
        message: 'Invalid or expired token',
      },
    });
  }

  // Parse JSON-RPC request
  const rpcRequest = req.body as JsonRpcRequest;

  if (!rpcRequest.jsonrpc || rpcRequest.jsonrpc !== '2.0') {
    return res.status(400).json({
      jsonrpc: '2.0',
      id: rpcRequest.id ?? null,
      error: {
        code: -32600,
        message: 'Invalid Request',
      },
    });
  }

  // Handle MCP methods
  const response = await handleMcpMethod(rpcRequest, userEmail);
  return res.status(200).json(response);
}

async function handleMcpMethod(
  request: JsonRpcRequest,
  userEmail: string
): Promise<JsonRpcResponse> {
  const { id, method, params } = request;

  switch (method) {
    case 'initialize':
      return {
        jsonrpc: '2.0',
        id,
        result: {
          protocolVersion: '2024-11-05',
          capabilities: {
            tools: {},
          },
          serverInfo: {
            name: 'lab-mcp-server',
            version: '1.0.0',
          },
        },
      };

    case 'tools/list':
      return {
        jsonrpc: '2.0',
        id,
        result: {
          tools: [imageGenToolDefinition],
        },
      };

    case 'tools/call':
      return handleToolCall(id, params as { name: string; arguments: Record<string, unknown> }, userEmail);

    case 'ping':
      return {
        jsonrpc: '2.0',
        id,
        result: {},
      };

    default:
      return {
        jsonrpc: '2.0',
        id,
        error: {
          code: -32601,
          message: `Method not found: ${method}`,
        },
      };
  }
}

async function handleToolCall(
  id: string | number,
  params: { name: string; arguments: Record<string, unknown> },
  userEmail: string
): Promise<JsonRpcResponse> {
  const { name, arguments: args } = params;

  switch (name) {
    case 'generate_image':
      try {
        const result = await generateImage({
          prompt: args.prompt as string,
          size: args.size as '256x256' | '512x512' | '1024x1024',
          style: args.style as 'natural' | 'vivid',
        });

        return {
          jsonrpc: '2.0',
          id,
          result: {
            content: [
              {
                type: 'text',
                text: `Image generated successfully!\nURL: ${result.url}\nPrompt: ${result.prompt}\nGenerated by: ${userEmail}`,
              },
            ],
          },
        };
      } catch (err) {
        return {
          jsonrpc: '2.0',
          id,
          error: {
            code: -32000,
            message: `Image generation failed: ${err instanceof Error ? err.message : 'Unknown error'}`,
          },
        };
      }

    default:
      return {
        jsonrpc: '2.0',
        id,
        error: {
          code: -32601,
          message: `Unknown tool: ${name}`,
        },
      };
  }
}
